# https://github.com/shokohsc/charts/tree/main/charts/homer
homer:
  extraVolumes:
    volumes:
      - name: config
        configMap:
          name: homer
    volumeMounts:
      - name: config
        mountPath: /www/assets/config.yml
        subPath: config.yml
