apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wekan
  namespace: wekan
spec:
  encryptedData:
    mongo-url: AgBGAfPHs60ulwaI4+Yxngp3jSo6flFFkHsMtKCBxnn+Aub5yt8/IvpQoym35GKTYqi/ka77jSqZZWnX7LIs/dZ0m4AdIJZA3kEAM6qGef6zuMZaZWb0NCwJ5+vMV1xxBMmu7+KRBqz/IDSvFBe82S/38KtWwoupqaQlka2o2+wg2QslAHP9GPoJyy16WikVK3VN4+zDBAXvVWN+7PXFrt7DPbgewilCNZ7LsGCSV8ppP92Rgn/TkNUzTJnCFAJXxFCjymVu5fe/NlO3SqqH/IG1+2/vlAC3DcC0MPprNo7jNuC23TUwvhGB52/i2cX4BFf5X4Li1+dy/AlC9VqEkYwv1ngHJzTr0IqOCi920OeH4SsarSpSfL7LFZfcFPVD2XfBDHcUeCXHjhCc7frnv/XVrNSYB4Hq+0f9a341obHFvm+05GIBxhhDEtrH7GEaFY9ovFNipSgFTS2ZM23cZNjjAxD+mCBvKWxNlLB8xnYw1VSwqrTlZ4iMPj3/fPEVxJcgIfnSX2Zs/+0z5YjTQJ/Rkb5aze18OtR7HFUWwKnHsQeq8jPUZjEp9z0FCQFhWnVc0JlikiHh14WF5Ta2ZTvV8UYBfHng8Rym/Iri5HlnbBES39krwSF28X+kuHaAwZa4B50Up/Ys4DRYP2C2UE4aQlhdIIewocArdJB/vprYqAtOdDQPyLKpWF1llvwiQBU2WFlNQcKLErwId1ScC4rvubYsIGl5M9f6i3llr4HDdqlEPs7/0U0nuKX8qqEIyxXS77S8wsS7
  template:
    metadata:
      creationTimestamp: null
      name: wekan
      namespace: wekan
