---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: wekan
  namespace: wekan
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`wekan.kind.lucio.home`)
    priority: 0
    services:
    - kind: Service
      name: wekan
      port: 8080
