# https://github.com/shokohsc/charts/tree/main/charts/openvpn-server
openvpn-server:
  externalHostname: openvpn.kind.lucio.home
  service:
    protocol: UDP
    type: LoadBalancer
    port: 41194
    fallback: true
    annotations:
      metallb.universe.tf/allow-shared-ip: "true"
  extraOptions:
    - 'management 0.0.0.0 5555'
    - 'push "redirect-gateway def1 bypass-dhcp"'
  persistence:
    existingClaim: openvpn-data
  easyrsa:
    caExpire: 30
    certExpire: 30
    crlDays: 30
    secret:
      enabled: true
      existingSecret: openvpn-server

image:
  repository: busybox
  tag: latest
resources: {}
persistence:
  existingClaim: openvpn-data
