# https://github.com/shokohsc/charts/tree/main/charts/openvpn-server
openvpn-server:
  externalHostname: openvpn.kind.lucio.home
  service:
    protocol: UDP
    type: LoadBalancer
    port: 41194
    fallback: true
  extraOptions:
    - 'management 0.0.0.0 5555'
    - 'push "redirect-gateway def1 bypass-dhcp"'
  persistence:
    existingClaim: openvpn-data

image:
  repository: busybox
  tag: latest
resources: {}
persistence:
  existingClaim: openvpn-data
