apiVersion: v2
name: openvpn-client
description: openvpn-client
type: application

version: 0.1.0

dependencies:
  - name: openvpn-client
    version: 0.2.1
    repository: https://shokohsc.github.io/charts
