# https://github.com/shokohsc/charts/tree/main/charts/openvpn-client
openvpn-client:
  envVars:
    FIREWALL: "''"
    ROUTE: 10.0.0.0/8
    TZ: Europe/Paris

  extraPorts:
    - name: peerflix
      containerPort: 9000
      protocol: TCP
    - name: transmission
      containerPort: 9091
      protocol: TCP

  extraVolumes:
    volumes:
      - name: peerflix-data
        emptyDir: {}
      - name: transmission-data
        persistentVolumeClaim:
          claimName: transmission-data
      - name: transmission-config
        configMap:
          name: transmission-config
      - name: downloads
        nfs:
          server: nfs-downloads-0.nfs-downloads.nfs-downloads.svc.cluster.local
          path: /

  sidecars:
  - name: transmission
    image: linuxserver/transmission
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - curl
          - -lsX
          - GET
          - "http://localhost:9091"
    readinessProbe:
      exec:
        command:
          - curl
          - -lsX
          - GET
          - "http://localhost:9091"
    startupProbe:
      exec:
        command:
          - curl
          - -lsX
          - GET
          - "http://localhost:9091"
    volumeMounts:
      - name: transmission-settings
        mountPath: /cfg/settings.json
        subPath: settings.json
      - name: transmission-data
        mountPath: /downloads/incomplete
      - name: downloads
        mountPath: /downloads/complete
        subPath: transmission
  - name: peerflix
    image: shokohsc/peerflix-server
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - curl
          - -lsX
          - GET
          - "http://localhost:9000"
    readinessProbe:
      exec:
        command:
          - curl
          - -lsX
          - GET
          - "http://localhost:9000"
    startupProbe:
      exec:
        command:
          - curl
          - -lsX
          - GET
          - "http://localhost:9000"
    volumeMounts:
      - name: peerflix-data
        mountPath: /tmp/torrent-stream
  # - name: cloudtorrent
  #   image:
  #     repository: shokohsc/cloud-torrent
  #     tag: latest
  #     pullPolicy: IfNotPresent
  #   service:
  #     type: ClusterIP
  #     port: 3000
  #     annotations: {}
  #   annotations: {}
  #   persistence:
  #     - name: data
  #       mountPath: /downloads
  #       accessModes:
  #         - ReadWriteOnce
  #       size: 10Gi
  #       annotations: {}
  #   envVars: {}
  #   resources: {}
  #   startupProbe: "ps -fe | grep 'clo[u]d-torrent'"
  # - name: deluge
  #   image:
  #     repository: linuxserver/deluge
  #     tag: latest
  #     pullPolicy: IfNotPresent
  #   service:
  #     type: ClusterIP
  #     port: 8112
  #     annotations: {}
  #   annotations: {}
  #   persistence:
  #     - name: config
  #       mountPath: /config
  #       accessModes:
  #         - ReadWriteOnce
  #       size: 200Mi
  #       annotations: {}
  #     - name: data
  #       mountPath: /downloads
  #       accessModes:
  #         - ReadWriteOnce
  #       size: 10Gi
  #       annotations: {}
    #   - name: download-incomplete
    #     mountPath: /downloads/incomplete
    #     accessModes:
    #       - ReadWriteOnce
    #     size: 10Gi
    #     annotations: {}
    # nfs:
    #   - name: download-complete
    #     server: nfs-downloads-0.nfs-downloads.nfs-downloads.svc.cluster.local
    #     path: /
    #     mountPath: /downloads/complete
        # subPath: deluge
    # configMap:
    #   name: deluge-settings
    #   mountPath: /cfg
    #   source: /cfg/core.conf
    #   target: /config/core.conf
  #   envVars:
  #     TZ: UTC
  #     DELUGE_LOGLEVEL: error
  #   resources: {}
  #   startupProbe: "ps -fe | grep '/usr/bin/python3 /usr/bin/del[u]ged -c /config -d'"
