---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openvpn-data
  labels:
    app.kubernetes.io/name: openvpn-server
    helm.sh/chart: openvpn-server
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
