---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openvpn-data
  labels:
    app.kubernetes.io/name: openvpn-server
    helm.sh/chart: openvpn-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
