---
apiVersion: v1
kind: Service
metadata:
  name: openvpn-server-httpd
  labels:
    app.kubernetes.io/name: openvpn-server-httpd
    helm.sh/chart: openvpn-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: openvpn-server-httpd
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
