---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: tekton
  namespace: tekton
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`tekton.kind.lucio.home`)
    priority: 0
    services:
    - kind: Service
      name: tekton-dashboard
      port: 9097
