---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: commander
  name: commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commander
  template:
    metadata:
      labels:
        app: commander
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: overwatch
                operator: NotIn
                values:
                - sombra
      hostname: commander
      containers:
      - image: coderaiser/cloudcmd
        name: commander
      #   volumeMounts:
      #       # name must match the volume name below
      #       - name: data-host-vol
      #         mountPath: "/root/media"
      # volumes:
      # - name: data-host-vol
      #   nfs: 
      #     # URL for the NFS server
      #     server: 192.168.1.63 # Change this!
      #     path: /
---
kind: Service
apiVersion: v1
metadata:
  name: commander-lb
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: commander
  # type: LoadBalancer
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: commander-ingr
spec:
  entryPoints: 
    - web
  routes:
  - match: Host(`kind.shokohsc.home`) 
    kind: Rule
    services:
    - name: commander-lb
      port: 80

