# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nfs-pv
# spec:
#   capacity:
#     storage: 10Mi
#   accessModes:
#     - ReadWriteMany
#   nfs:
#     # server: nfs-service.default.svc.cluster.local
#     server: "10.164.18.63"
#     path: "/"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nfs-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: ""
#   resources:
#     requests:
#       storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: commander
  name: commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commander
  template:
    metadata:
      labels:
        app: commander
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: overwatch
                operator: In
                values:
                - sombra
      containers:
      - image: coderaiser/cloudcmd
        name: commander
        # ports:
        # - containerPort: 8000
        #   name: web
        volumeMounts:
            # name must match the volume name below
            - name: data-host-vol
              mountPath: "/root/media"
      hostname: commander
      volumes:
      - name: data-host-vol
        hostPath:
          path: /data
        # persistentVolumeClaim:
        #   claimName: rook-nfs-pv-claim
        # persistentVolumeClaim:
        #   claimName: nfs-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: commander-lb
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: commander
  type: LoadBalancer
