apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: h5ai
  name: h5ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: h5ai
  template:
    metadata:
      labels:
        app: h5ai
    spec:
      containers:
      - image: corfr/h5ai
        name: h5ai
        volumeMounts:
            # name must match the volume name below
            - name: rook-nfs-vol
              mountPath: "/mnt"
            - name: rook-nfs-vol
              mountPath: "/var/www/"
      hostname: h5ai
      volumes:
      - name: rook-nfs-vol
        persistentVolumeClaim:
          claimName: rook-nfs-pv-claim
