apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: h5ai
  name: h5ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h5ai
  template:
    metadata:
      labels:
        app: h5ai
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: overwatch
                operator: In
                values:
                - sombra
      containers:
      - image: corfr/h5ai
        name: h5ai
        volumeMounts:
            # name must match the volume name below
            - name: rook-nfs-vol
              mountPath: "/var/www"
      hostname: h5ai
      volumes:
      - name: rook-nfs-vol
        hostPath:
          path: /mnt
        # persistentVolumeClaim:
        #   claimName: rook-nfs-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"