# kubectl taint nodes --all node-role.kubernetes.io/master-
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  # kubeProxyMode: "ipvs"
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "127.0.0.1"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node.overwatch.io/character=sombra,node.longhorn.io/create-default-disk=true"
#         node-labels: "node.overwatch.io/character=hammond"
  # add a mount from /path/to/my/files on the host to /files on the node
  # extraMounts:
  # - hostPath: /mnt
  #   containerPath: /mnt
  # - hostPath: /home/sombra/storage/sombra
  #   containerPath: /storage
  # image: kindest/node:v1.18.8@sha256:f4bcc97a0ad6e7abaf3f643d890add7efe6ee4ab90baeb374b4f41a4c95567eb

- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node.overwatch.io/character=lucio,node.longhorn.io/create-default-disk=true"
#         node-labels: "node.overwatch.io/character=lucio"
  extraMounts:
  # - hostPath: /home/sombra/storage/lucio
  #   containerPath: /storage
  # image: kindest/node:v1.18.8@sha256:f4bcc97a0ad6e7abaf3f643d890add7efe6ee4ab90baeb374b4f41a4c95567eb

- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node.overwatch.io/character=zarya,node.longhorn.io/create-default-disk=true"
#         node-labels: "node.overwatch.io/character=zarya"
#   extraMounts:
#   - hostPath: /home/sombra/storage/zarya
#     containerPath: /storage
#   # image: kindest/node:v1.18.8@sha256:f4bcc97a0ad6e7abaf3f643d890add7efe6ee4ab90baeb374b4f41a4c95567eb

- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node.overwatch.io/character=hammond"
#         node-labels: "node.overwatch.io/character=sombra,node.longhorn.io/create-default-disk=true"
#       taints:
#         - effect: NoSchedule
#           key: node.kubernetes.io/sombra
#  extraMounts:
  # - hostPath: /home/sombra/storage/sombra
  #   containerPath: /storage
  # image: kindest/node:v1.18.8@sha256:f4bcc97a0ad6e7abaf3f643d890add7efe6ee4ab90baeb374b4f41a4c95567eb

# - role: worker
#   kubeadmConfigPatches:
#   - |
#     kind: JoinConfiguration
#     nodeRegistration:
#       kubeletExtraArgs:
#         node-labels: "node.overwatch.io/character=torbjorn,node.longhorn.io/create-default-disk=true"
#   # extraMounts:
#   # - hostPath: /home/sombra/storage/torbjorn
#   #   containerPath: /storage
#   # image: kindest/node:v1.18.8@sha256:f4bcc97a0ad6e7abaf3f643d890add7efe6ee4ab90baeb374b4f41a4c95567eb
#
# - role: worker
#   kubeadmConfigPatches:
#   - |
#     kind: JoinConfiguration
#     nodeRegistration:
#       kubeletExtraArgs:
#         node-labels: "node.overwatch.io/character=mercy,node.longhorn.io/create-default-disk=true"
#   # extraMounts:
#   # - hostPath: /home/sombra/storage/mercy
#   #   containerPath: /storage
#   # image: kindest/node:v1.18.8@sha256:f4bcc97a0ad6e7abaf3f643d890add7efe6ee4ab90baeb374b4f41a4c95567eb

# featureGates:
#   DynamicKubeletConfig: true
#   ExecProbeTimeout: true
#   ExpandInUsePersistentVolumes: true
#   ExpandPersistentVolumes: true
#   GenericEphemeralVolume: true
#   GracefulNodeShutdown: true
#   MixedProtocolLBService: true
#   PodDisruptionBudget: true
#   RunAsGroup: true
#   SCTPSupport: true
#   SetHostnameAsFQDN: true
#   SupportPodPidsLimit: true
#   TaintBasedEvictions: true
#   TaintNodesByCondition: true
#   TTLAfterFinished: true
#   VolumeSubpathEnvExpansion: true

# kubeadmConfigPatches:
#   - |
#     kind: ClusterConfiguration
#     metadata:
#       name: config
#     etcd:
#       local:
#         dataDir: "/dev/shm/etcd"
# #     apiServer:
# #       extraArgs:
# #         allow-privileged: "true"
