---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: heimdall
  namespace: heimdall
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: "Host(`heimdall.{{ .Values.domain }}`)"
    priority: 0
    services:
    - kind: Service
      name: heimdall
      port: 80
