# https://github.com/shokohsc/charts/tree/main/charts/plex
samba:
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: "true"
  args:
    - -s
    - "shared;/mnt;yes;no;yes;all;none"
    - -p
  extraVolumes:
    volumeMounts:
    - name: wd1to
      mountPath: /mnt/WD1To
    - name: wd2to
      mountPath: /mnt/WD2To
    - name: shared
      mountPath: /mnt/shared
    - name: downloads
      mountPath: /mnt/downloads
    - name: backups
      mountPath: /mnt/backups
    volumes:
    - name: wd1to
      nfs:
        server: nfs-wd1to.nfs-wd1to.svc.cluster.local
        path: /
    - name: wd2to
      nfs:
        server: nfs-wd2to.nfs-wd2to.svc.cluster.local
        path: /
    - name: shared
      nfs:
        server: nfs-shared.nfs-shared.svc.cluster.local
        path: /
    - name: downloads
      nfs:
        server: nfs-downloads.nfs-downloads.svc.cluster.local
        path: /
    - name: backups
      nfs:
        server: nfs-backups.nfs-backups.svc.cluster.local
        path: /
