# https://github.com/shokohsc/charts/tree/main/charts/commafeed
commafeed:
  initContainers:
    - name: 00-sed
      image: busybox
      env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: commafeed
              key: postgresql-password
        - name: CACHE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: commafeed
              key: redis-password
      command:
        - /bin/sh
      args:
        - -c
        - sed "s/%%DATABASE_PASSWORD%%/${DATABASE_PASSWORD}/g" /tmp/config.yml | sed "s/%%CACHE_PASSWORD%%/${CACHE_PASSWORD}/g" /tmp/config.yml > /config/config.yml
      volumeMounts:
        - name: commafeed-config
          mountPath: /tmp/config.yml
          subPath: config.yml
        - name: config
          mountPath: /tmp
  extraVolumes:
    volumeMounts:
      - name: config
        mountPath: /config
    volumes:
      - name: commafeed-config
        configMap:
          name: commafeed-config
          defaultMode: 0664
      - name: config
        emptyDir: {}
