---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/shokohsc/kind-test.git
    path: applications/traefik
    targetRevision: HEAD
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
