---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: cluster
    server: https://kubernetes.default.svc
  project: traefik
  syncPolicy:
    automated:
      prune: true
  source:
    path: applications
    repoURL: https://github.com/shokohsc/kind-test.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
