---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/shokohsc/kind-test.git
    path: applications
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
