apiVersion: v2
name: postgresql-ha
description: postgresql-ha
type: application

version: 0.1.0

dependencies:
  - name: postgresql-ha
    version: 6.5.5
    repository: https://charts.bitnami.com/bitnami
