---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.kind.shokohsc.home`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  name: linkerd
  namespace: linkerd
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: Host(`linkerd.kind.shokohsc.home`)
    priority: 0
    services:
    - kind: Service
      name: linkerd-web
      port: 8084

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  name: adminer
  namespace: adminer
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: Host(`adminer.kind.shokohsc.home`)
    priority: 0
    services:
    - kind: Service
      name: adminer
      port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  name: argocd
  namespace: argocd
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: Host(`argocd.kind.shokohsc.home`)
    priority: 0
    services:
    - kind: Service
      name: argocd-server
      port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  name: dashboard
  namespace: dashboard
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: Host(`dashboard.kind.shokohsc.home`)
    priority: 0
    services:
    - kind: Service
      name: kubernetes-dashboard
      port: 443