---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.kind.shokohsc.home`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: l5d-header-middleware
  namespace: linkerd
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "linkerd-web.linkerd.svc.cluster.local:8084"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  name: linkerd
  namespace: linkerd
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: Host(`linkerd.kind.shokohsc.home`)
    priority: 0
    middlewares:
    - name: l5d-header-middleware
    services:
    - kind: Service
      name: linkerd-web
      port: 8084

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: l5d-header-middleware
  namespace: adminer
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "adminer.linkerd.svc.cluster.local:80"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  name: adminer
  namespace: adminer
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: Host(`adminer.kind.shokohsc.home`)
    priority: 0
    middlewares:
    - name: l5d-header-middleware
    services:
    - kind: Service
      name: adminer
      port: 80