---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-wd1to
  namespace: nfs
spec:
  replicas: 1
  selector:
    role: nfs-wd1to
  template:
    metadata:
      labels:
        role: nfs-wd1to
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: overwatch
                operator: In
                values:
                - sombra
      containers:
      - name: nfs
        imagePullPolicy: Always
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: wd1to
      volumes:
        - name: wd1to
          hostPath:
            path: /mnt/WD1To
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-wd1to
  namespace: nfs
spec:
  ports:
    - name: nfs
      port: 2049
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
    - name: mountd
      port: 20048
  selector:
    role: nfs-wd1to

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-wd2to
  namespace: nfs
spec:
  replicas: 1
  selector:
    role: nfs-wd2to
  template:
    metadata:
      labels:
        role: nfs-wd2to
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: overwatch
                operator: In
                values:
                - sombra
      containers:
      - name: nfs
        imagePullPolicy: Always
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: wd2to
      volumes:
        - name: wd2to
          hostPath:
            path: /mnt/WD2To
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-wd2to
  namespace: nfs
spec:
  ports:
    - name: nfs
      port: 2049
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
    - name: mountd
      port: 20048
  selector:
    role: nfs-wd2to
