---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: loki-stack
  namespace: loki-stack
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: "Host(`grafana.{{ .Values.domain }}`)"
    priority: 0
    services:
    - kind: Service
      name: loki-stack-grafana
      port: 80
