---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: theia
  namespace: theia
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`theia.kind.lucio.home`)
    priority: 0
    services:
    - kind: Service
      name: theia
      port: 3000
