apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfs.fullname" . }}
  labels:
    {{- include "nfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $name, $config := .Values.ports }}
    - port: {{ default $config.port $config.exposedPort }}
      name: {{ $name }}
      targetPort: {{ $name | quote }}
      protocol: {{ default "TCP" $config.protocol | quote }}
      {{- if $config.nodePort }}
      nodePort: {{ $config.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "nfs.selectorLabels" . | nindent 4 }}
