nfs:
  volumes:
    - name: storage
      mountPath: /storage
      path: /storage

  replicaCount: 1

  nodeSelector:
    overwatch: sombra

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: NotIn
              values:
              - nfs
          topologyKey: "kubernetes.io/hostname"
