{{- $ctx := . }}
{{- range $volume := .Values.extraVolumes }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "plex.fullname" $ctx }}-{{ $volume.name }}
  labels: {{- include "plex.labels" $ctx | nindent 4 }}
  annotations:
    {{- with $volume.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  {{- range $volume.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $volume.size | quote }}
  {{ include "plex.storageClass" $ctx }}
{{- end }}
