---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.kind.shokohsc.home`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: traefik
#   name: linkerd
#   namespace: linkerd
# spec:
#   entryPoints:
#     - web
#   routes:
#   - kind: Rule
#     match: Host(`linkerd.kind.shokohsc.home`)
#     priority: 0
#     services:
#     - kind: Service
#       name: linkerd-web
#       port: 8084

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirectscheme
spec:
  redirectScheme:
    scheme: https
    permanent: true