# https://github.com/shokohsc/charts/tree/main/charts/plex
plex:
  image:
    repository: linuxserver/plex
    tag: latest
  service:
    annotations:
      metallb.universe.tf/allow-shared-ip: "true"
  envVars:
    HOSTNAME: ""
    PLEX_CLAIM: ""
    TZ: Europe/Paris
    ADVERTISE_IP: 'http://172.19.0.64:32400'
    CHANGE_CONFIG_DIR_OWNERSHIP: true
    ALLOWED_NETWORKS: 10.0.0.0/8
    VERSION: docker
  extraPorts:
    - name: dlna-udp
      containerPort: 1900
      protocol: UDP
      type: LoadBalancer
    - name: dlna-tcp
      containerPort: 32469
      protocol: TCP
      type: LoadBalancer
    - name: gdm-first
      containerPort: 32410
      protocol: UDP
      type: LoadBalancer
    - name: gdm-second
      containerPort: 32412
      protocol: UDP
      type: LoadBalancer
    - name: gdm-third
      containerPort: 32413
      protocol: UDP
      type: LoadBalancer
    - name: gdm-fourth
      containerPort: 32414
      protocol: UDP
      type: LoadBalancer
  extraVolumes:
    volumes:
      - name: wd1to
        nfs:
          server: nfs-wd1to.nfs-wd1to.svc.cluster.local
          path: /
      - name: wd2to
        nfs:
          server: nfs-wd2to.nfs-wd2to.svc.cluster.local
          path: /
      - name: plex-data
        persistentVolumeClaim:
          claimName: plex-data
    volumeMounts:
      - name: wd1to
        mountPath: /data/WD1To
      - name: wd2to
        mountPath: /data/WD2To
      - name: plex-data
        mountPath: /config
