---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: homer
  namespace: homer
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: "Host(`homer.{{ .Values.domain }}`)"
    priority: 0
    services:
    - kind: Service
      name: homer
      port: 80
