apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBfv009bL4Znk6HHmq/mazl1YcxDsjADltteArwEoIXufZR/tFvlBqXJFNYc/oatG61fHbl7jz5oI7Zf8jY08FNeRWIINLD6BaEXEFctqiLJo28zt4+5Q+tIQrUFFh5TpUU/hv6Wcq53mZklGLMxUBTHUogrEFI+zBQX3kjTm0NPffVimSwVRT35vDEVwK8iKAmDJdZebp1LSeKoM7YoWxZC9/Nxrn6o4phF9ZuZVZNA3cuy2k1tkjpg2MQPxAegyzjAzN3eDNsJgiJ9Nymt31I5Vwf0qHZ+v6fu5A9IgxPbqKA+p2juC+k+GKjXELWRbgk7ihztc5ra4m58lFIaoJGZq4IVXmxDnzILQP3utA929h5DJHI3V688hn3PURhR98BsZs0MyxPKz9ROwCy4EvOBp2KOME1od4/4oH3y6COfipq3nzFv7yc2+e3AlKtuvwdcXXS9Wb1XQsglbjavXVQjtktjFxFvIi0lNnbYZT0UfyD/X9cKxPvIGxhoi70E2xqDhsEPvkvKMqPAstLhJHB/DkFJdztF0qqD045Ka8cGOkwgKnMQQ3Ilqh/5XXFwHc+lXocc6a/du8lyVRmH02knBHY3n/0F1+7P4OynbmHVe2WQL7CPHzW8UxGw1b/QoDmCS5085/dS2yX4TNskJi51hjjUnyxinsNIu9UCcE4T2i01UK1lxLID7TNhX/uu2WVLFVkUxFt3i14LA==
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: redis
