apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBjvbC2ZFRC6uvIP94M9GK+zInPBPO4HbRFRLW7uwspSzW7Z8rIMMvu246k1HPSZlNiPwOlP+BfYdaI53MkzDAHWX/BHzcC+psmx31O96CppDI5dtZ+FYZwve1nE7RF9aQ07ACsM0aAYaAEzD0gWHkKNmx0Cncpag8x3F18oyy7nIdfZvCej9kUFNsvtDQ/qr0bIY69nwMxUWmmKDiGLmj0l3XJenducM/ZK+ekuMa4esI1aeYHzWNr8QwLy3xcq1U0OEdpzqNBH2Jhc/YjImQZDni3aCZS+Z1JKRtK0muZ+wxw6UClbC2g15lJ00NCKCMvTECxfWEKTS1f+Al4LAUVmZftknuaGFEoyNE6iLcFdafmajUZFeFubfITv/VeiMQ2ZHdr0p7KMj4eFQkxXGYAyLi+ZwaALSxKKpyMznIh9nUKvK598GMilAPi7iVV+WaXLRH8zrxShjwCwrIe8xFKLrwudFQgjk9VT0uK3Rq3ozVC47HmNBVRs+J+jhxltfAQDM1uMZHGQoqAvcRbFcBjg4BzQTv4Nyw+DzxoQS9z7SMhV4WC1xURNRDpzqqZBN5rSvr5TnaKmT2/t2b1Xu5QbE4oPBEJXgql25WR9V+H+/44hodItcMl1AkQphLslbLZCNQm9aKgwqcubjobX6Sdhlri2Zgp2KcPN+CX9VmuKJHml/Eb+FL/TDWl3XwzQgdfnqzxNePe3IwFeg==
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: redis
