apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgCKjexCMTYaEzgFjE9Wf4tFaG1T5X2itCzjKvKX9q5p/3QBx6QOA+l5wiKdJpzjYgepepyw9cXy6VJny5iRC96qFXidW8WbOe11EAYAaTl9kNI8PB3ZcoOfmLxGEaqEMjMfTJOwukIHpNiqumxbm1/x/c0nQqGiW/48yHgj43BO6ycopSIrasal3NPVZeO4XRUIMNR7VV2eXlj4Eit0u8Og6Xi16Sp11wLBXWYeerIoL4xPkAtF0PAhN24DCpvrLuqOZyIOo6YE71WgWIuyYGOszHFmATYZxCIUblP+mrSfKJnKjiSxFosctRKyqRbUvPLQGQBJxyjsyN000asOfKbiEgTkMsEnx3W1b6SacMu3x2k1l1Wx4j5YwDUQP1yFGF6T5ADaN/0zQnmQWmlyCm8qszjpYV/jJrkN/q1pcISMwEK/9KwptMHou0/W++qyJE0N27BZez8aE/aA20XTKt00eYrCfscYhogBWJk6mPHlVHtBbajahnofzEAlJglt8nRJv9zH1bnRsQAU0FR+6yAMdEqizL/+hwFKnIUSk3EI60kEt2CPfvnjuzggAW73U9FhTNUeJxV6JPY9Sei9e9lPYbi3xrqQr1i2mcMKfM6M37imnqvNJ3+74g13nMGEp5OhLroSz4LZMkh4z/JLVI0WBWfcUwOnO3bcLjpcx9O+0xdRRcoNCyCHHr4Y3dgfY7O/Bx+2DQk5MMapIw==
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: redis
