apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgAZZstAK+9pps2x9xvCQnqz/DqssBfhZ/ivuAn/VHFLO2mg4Ea9AdBuB1oHBz+30x0JqmYTk964JXxPYJpZv6LDeQIcbEUoA1SPco92NIbttNI2wvU4Bl93B60UUXSUPEseur+UCXTwRCi5dCmFepW1/42BGm2Y9Ip0zZjy8T2cqvJYh1XHk5g4vk5+CWERIY1p43FRTFJzvzx6c1smMVqsnN04BwPGxcj0ZuNjxCxDClRmPM4e2SVj57NC7pS1KAHujtiVOtxw20ZkQilbFymRqz5FS3vOW2liwXXK3KhDLg4HdyqNktN2BYUgzU5+k33yWa3McsvuvZ8FmkDLLt4pISpK+FVGwx747pbVoxNZTWZP2EiWbUbtiogSfJgf+2r7WrgOMjsub9my1QYA3+r+rk732J7ALevpKyWGFs9ZGjC6dmVoOQo7xSD3MftSQXu83nG8JxUEdI5OjgXMXb6Jjb0Qc/DpeGiD+o+bcp2HFKLsbmhpjXOUXV+UUYvO0/RU8rv+l9ka6+f9OHn5C7VFjmlbl3ltA4GXNRSozXQw9Trzk31a92H667ngipekROQlgyMC30wGCpnseIAleNRmAt7cHmPc/wOnw3rz1m3iSLrwBcIWOea7j8f8GuzkQL8P68eFKgpcZ5XfgQsYGpxSRsdGhZ+6IlDPhcxvS4VT4U2/XMEzebJyJpbfD6FDH+OPFifcYoe9SNwUKA==
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: redis
