# https://github.com/shokohsc/charts/tree/main/charts/pihole
pihole:
  virtualHost: pihole.kind.shokohsc.home
  timezone: Europe/Paris
  persistentVolumeClaim:
    enabled: true
    storageClass: nfs
  dns:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"
  dhcp:
    enabled: true
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"
  doh:
    enabled: true
  dnsmasq:
    upstreamServers:
      - server=/cluster.local/10.96.0.10
  extraEnvVars:
    DNSMASQ_LISTENING: all
