# https://github.com/shokohsc/charts/tree/main/charts/pihole
pihole:
  virtualHost: pihole.kind.lucio.home
  timezone: Europe/Paris
  existingClaim: pihole-data
  dns:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"
  doh:
    enabled: true
  dnsmasq:
    upstreamServers:
      - server=/cluster.local/10.96.0.10
  extraEnvVars:
    DNSMASQ_LISTENING: all

  extraVolumes:
    volumes:
      - name: pihole
        persistentVolumeClaim:
          claimName: pihole-data
    volumeMounts:
      - name: pihole
        mountPath: /etc/pihole
