# https://github.com/shokohsc/charts/tree/main/charts/pihole
pihole:
  virtualHost: pihole.kind.shokohsc.home
  timezone: Europe/Paris
  dns:
    service:
      type: LoadBalancer
  dhcp:
    enabled: true
    service:
      type: LoadBalancer
  doh:
    enabled: true
  dnsmasq:
    upstreamServers:
      - server=/cluster.local/10.96.0.10
  extraEnvVars:
    DNSMASQ_LISTENING: all
  service:
    annotations:
      metallb.universe.tf/allow-shared-ip: "true"
