# https://github.com/shokohsc/charts/tree/main/charts/nfs
nfs:
  extraVolumes:
    volumes:
      - name: wd2to
        hostPath:
          path: /mnt/WD2To
    volumeMounts:
      - name: wd2to
        mountPath: /wd2to
  nodeSelector:
    node.overwatch.io/character: sombra
