# https://github.com/bitnami/charts/tree/master/bitnami/mongodb
mongodb:
  global:
    storageClass: nfs
  architecture: replicaset
  useStatefulSet: true
  directoryPerDB: true
  # auth:
  #   enabled: true
  #   existingSecret:
