---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: goldilocks
  namespace: goldilocks
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`goldilocks.kind.lucio.home`)
    priority: 0
    services:
    - kind: Service
      name: goldilocks-dashboard
      port: 80
