# https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd
argo-cd:
  ## Server
  server:
    ## Additional command line arguments to pass to argocd-server
    extraArgs:
    - --insecure
    - --disable-auth
  global:
    image:
      tag: v1.8.1
