# https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd
argo-cd:
  ## Server
  server:
    ## Additional command line arguments to pass to argocd-server
    extraArgs:
    - --insecure
    config:
      url: https://argocd.kind.shokohsc.home
      repositories: |
        - type: helm
          url: https://charts.helm.sh/stable
          name: stable
  global:
    image:
      tag: v1.8.1
