---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    namespace: cert-manager
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
    retry:
      limit: 2
  source:
    repoURL: {{ .Values.repoUrl }}
    path: charts/cert-manager
    targetRevision: HEAD
    helm:
      values: |
        domain: {{ .Values.domain }}
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
