---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commander
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Validate=true
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/shokohsc/kind-test.git
    path: charts/commander
    targetRevision: HEAD
  destination:
    namespace: commander
    server: https://kubernetes.default.svc
