---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commander
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
  source:
    repoURL: https://github.com/shokohsc/kind-test.git
    path: charts/commander
    targetRevision: HEAD
  destination:
    namespace: commander
    server: https://kubernetes.default.svc
