# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: kube-prometheus-stack
#   labels:
#     namespace: kube-prometheus-stack
#     goldilocks.fairwinds.com/enabled: "true"
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kube-prometheus-stack
#   namespace: argocd
# spec:
#   project: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - Validate=true
#     retry:
#       limit: 2
#   source:
#     repoURL: {{ .Values.repoUrl }}
#     path: charts/kube-prometheus-stack
#     targetRevision: HEAD
#     helm:
#       values: |
#         domain: {{ .Values.domain }}
#   destination:
#     namespace: kube-prometheus-stack
#     server: https://kubernetes.default.svc
