---
apiVersion: v1
kind: Namespace
metadata:
  name: loki-stack
  labels:
    namespace: loki-stack
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
    retry:
      limit: 2
  source:
    repoURL: {{ .Values.repoUrl }}
    path: charts/loki-stack
    targetRevision: HEAD
    helm:
      values: |
        domain: {{ .Values.domain }}
  destination:
    namespace: loki-stack
    server: https://kubernetes.default.svc
