---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-express
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
    retry:
      limit: 2
  source:
    repoURL: https://github.com/shokohsc/kind-test.git
    path: charts/mongo-express
    targetRevision: HEAD
  destination:
    namespace: mongo-express
    server: https://kubernetes.default.svc
