---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-wd1to
  labels:
    namespace: nfs-wd1to
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-wd1to
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
    retry:
      limit: 2
  source:
    repoURL: https://github.com/shokohsc/kind-test.git
    path: charts/nfs-wd1to
    targetRevision: HEAD
  destination:
    namespace: nfs-wd1to
    server: https://kubernetes.default.svc
