---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server-provisioner
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
    retry:
      limit: 2
  source:
    repoURL: https://github.com/shokohsc/kind-test.git
    path: charts/nfs-server-provisioner
    targetRevision: HEAD
  destination:
    namespace: nfs-server-provisioner
    server: https://kubernetes.default.svc
