---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-wd2to
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
    retry:
      limit: 2
  source:
    repoURL: https://github.com/shokohsc/kind-test.git
    path: charts/nfs-wd2to
    targetRevision: HEAD
  destination:
    namespace: nfs
    server: https://kubernetes.default.svc
