---
apiVersion: v1
kind: Namespace
metadata:
  name: plex
  labels:
    namespace: plex
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
    retry:
      limit: 2
  source:
    repoURL: https://github.com/shokohsc/kind-test.git
    path: charts/plex
    targetRevision: HEAD
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
