---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/shokohsc/kind-test.git
    path: charts/postgresql
    targetRevision: HEAD
  destination:
    namespace: postgresql
    server: https://kubernetes.default.svc
