---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
  labels:
    namespace: sealed-secrets
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
    retry:
      limit: 2
  source:
    repoURL: {{ .Values.repoUrl }}
    path: charts/sealed-secrets
    targetRevision: HEAD
    helm:
      values: |
        domain: {{ .Values.domain }}
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
