---
apiVersion: v1
kind: Namespace
metadata:
  name: vertical-pod-autoscaler
  labels:
    namespace: vertical-pod-autoscaler
    goldilocks.fairwinds.com/enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vertical-pod-autoscaler
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
    retry:
      limit: 2
  source:
    repoURL: https://github.com/shokohsc/kind-test.git
    path: charts/vertical-pod-autoscaler
    targetRevision: HEAD
  destination:
    namespace: vertical-pod-autoscaler
    server: https://kubernetes.default.svc
