# https://github.com/grafana/helm-charts/tree/main/charts/loki-stack
loki-stack:
  grafana:
    enabled: true
    grafana-ini:
      users:
        disable_login_form: true
      security:
        disable_initial_admin_creation: true
