# https://github.com/shokohsc/charts/tree/main/charts/nfs
nfs:
  extraVolumes:
    volumes:
      - name: backups
        hostPath:
          path: /mnt/backups
    volumeMounts:
      - name: backups
        mountPath: /backups
  nodeSelector:
    node.overwatch.io/character: lucio
