---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: comics
  namespace: comics
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: "Host(`comics.{{ .Values.domain }}`)"
    priority: 0
    services:
    - kind: Service
      name: comics-symfony
      port: 80
