kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  symfony.conf: |
    server {

        root /var/www/symfony/public;

        # Used to get the real client ip, we are behind a loadbalancer
        set_real_ip_from 0.0.0.0/0;
        real_ip_header X-Real-IP;
        real_ip_recursive on;


        location / {
            try_files $uri @rewriteapp;
        }

        location @rewriteapp {
            rewrite ^(.*)$ /index.php/$1 last;
        }

        location ~ ^/(index)\.php(/|$) {
            fastcgi_pass localhost:9000;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTPS off;
            fastcgi_read_timeout 600;
        }

        error_log /dev/stderr;
        access_log /dev/stdout;
    }
