apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comics.fullname" . }}
  labels:
    {{- include "comics.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "comics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "comics.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "comics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      initContainers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c", "cp -r /var/www/symfony/. /app"]
          volumeMounts:
            - name: shared-files
              mountPath: /app

      containers:
        - name: php-fpm
          image: shokohsc/alpine-php-fpm
          env:
            {{- range $key, $value := .Values.envVars }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: php
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: php
          readinessProbe:
            tcpSocket:
              port: php
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/symfony
            {{- range .Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}

        - name: nginx
          image: shokohsc/alpine-nginx
          env:
            {{- range $key, $value := .Values.envVars }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/symfony

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: shared-files
          emptyDir: {}
        {{- range .Values.volumes }}
        - name: {{ .name }}
          nfs:
            server: {{ .server }}
            path: {{ .path }}
          {{- if .mountOptions }}
          mountOptions:
            {{- range .mountOptions }}
            - {{ . }}
            {{- end }}
          {{- end }}
        {{- end }}
