apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    {{- include "comics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9000
      targetPort: php
      protocol: TCP
      name: php
  selector:
    {{- include "comics.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "comics.fullname" . }}
  labels:
    {{- include "comics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "comics.selectorLabels" . | nindent 4 }}
