---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: thelounge
  namespace: thelounge
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: "Host(`irc.{{ .Values.domain }}`)"
    priority: 0
    services:
    - kind: Service
      name: thelounge
      port: 80
