# https://github.com/shokohsc/charts/tree/main/charts/nfs
nfs:
  volumes:
    - name: downloads
      mountPath: /downloads
      path: /mnt/downloads
  nodeSelector:
    node.overwatch.io/character: sombra
