# https://github.com/shokohsc/charts/tree/main/charts/nfs
nfs:
  extraVolumes:
    volumes:
      - name: downloads
        hostPath:
          path: /mnt/downloads
    volumeMounts:
      - name: downloads
        mountPath: /downloads
  nodeSelector:
    node.overwatch.io/character: zarya
