# https://github.com/shokohsc/charts/tree/main/charts/openvpn-server
openvpn-server:
  externalHostname: openvpn.kind.shokohsc.home
  service:
    protocol: UDP
    type: LoadBalancer
    fallback: true
    annotations:
      metallb.universe.tf/allow-shared-ip: "true"
  extraOptions:
    - 'management 0.0.0.0 5555'
    - 'push "redirect-gateway def1 bypass-dhcp"'