---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: prometheus
  namespace: kube-prometheus-stack
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: "Host(`prometheus.{{ .Values.domain }}`)"
    priority: 0
    services:
    - kind: Service
      name: kube-prometheus-stack-prometheus
      port: 9090
