---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: grafana
  namespace: kube-prometheus-stack
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`grafana.kind.shokohsc.home`)
    priority: 0
    services:
    - kind: Service
      name: grafana
      port: 3000
