# https://github.com/shokohsc/charts/tree/main/charts/nfs
nfs:
  extraVolumes:
    volumes:
      - name: shared
        hostPath:
          path: /mnt/shared
    volumeMounts:
      - name: shared
        mountPath: /shared
  nodeSelector:
    node.overwatch.io/character: sombra
