---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: adminer
  namespace: adminer
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`adminer.kind.shokohsc.home`)
    priority: 0
    services:
    - kind: Service
      name: adminer
      port: 80
