# https://github.com/shokohsc/charts/tree/main/charts/wekan
wekan:
  envVars:
    ROOT_URL: https://wekan.kind.shokohsc.home
    MONGO_URL: mongodb://mongodb.mongodb/wekan
  mongodb:
    enabled: false
